# Generated by Django 5.1.1 on 2025-05-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=10)),
                ('car_name', models.CharField(max_length=100)),
                ('vehicle_details', models.TextField()),
                ('service_type', models.CharField(max_length=50)),
                ('specific_issues', models.TextField(blank=True)),
                ('appointment_time', models.DateTimeField()),
                ('preferred_mode', models.CharField(max_length=20)),
                ('customer_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
